name: Update Hashes

on:
  workflow_dispatch:
  push:

jobs:
  update-hashes:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Download latest release binary
        run: |
          URL=$(curl -s https://api.github.com/repos/CherretGit/zaprett-repo-utils/releases/latest \
            | jq -r '.assets[] | select(.name == "zaprett-repo-utils-linux-x86_64") | .browser_download_url')

          echo "Downloading: $URL"
          wget "$URL"

      - name: Make binary executable
        run: chmod +x zaprett-repo-utils-linux-x86_64

      - name: Run binary
        run: ./zaprett-repo-utils-linux-x86_64 update

      - name: Show diff
        run: git diff

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Автообновление: хэши, новые записи, очистка"
